### ISSUE TITLE
New version 2.0 was released, needs update + rebuild

### ISSUE THREAD

**Issue by rggjan** [conda-forge/aiobotocore-feedstock#42]
https://github.com/aio-libs/aiobotocore/releases/tag/2.0.0

**Comment by guenhter** [comment]
Even a newer version is already available:

https://github.com/aio-libs/aiobotocore/releases/tag/2.1.0

**Comment by guenhter** [comment]
@rggjan Version 2.0.0 and version 2.0.1 are available. Is this sufficient for you?

**Comment by nehaljwani** [comment]
https://anaconda.org/conda-forge/aiobotocore/2.1.0/download/noarch/aiobotocore-2.1.0-pyhd8ed1ab_0.tar.bz2

Should be available via CDN shortly.

**Comment by nehaljwani** [comment]
```
❯❯❯ conda search conda-forge::aiobotocore
...
...
...
aiobotocore                    2.0.0    pyhd8ed1ab_0  conda-forge
aiobotocore                    2.0.1    pyhd8ed1ab_0  conda-forge
aiobotocore                    2.1.0    pyhd8ed1ab_0  conda-forge
```
