### ISSUE TITLE
2.6.0 didn't build

### ISSUE THREAD

**Issue by martindurant** [conda-forge/aiobotocore-feedstock#68]
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

Even though https://github.com/conda-forge/aiobotocore-feedstock/pull/67 was green and auto-merged, the merge commit build ( https://app.circleci.com/pipelines/github/conda-forge/aiobotocore-feedstock/103 ) failed, and 2.6.0 never appeared for conda.

### Installed packages

```shell
x
```

### Environment info

```shell
x
```

**Comment by peterbygrave** [comment]
Tagging @nehaljwani as recipe maintainer

**Comment by martindurant** [comment]
Closed by #69
